### ISSUE TITLE
[chart] tooltips

### ISSUE THREAD

**Issue by nerdlich-media** [rajgoel/reveal.js-plugins#101]
The tooltip functionality is not working. are there any plans to implement this function ?

**Comment by rajgoel** [comment]
As the plugin just provides are wrapper for Chart.js I doubt that there is anything in the plugin preventing the tooltips to work, so the issue you have is likely somewhere else.

**Comment by artt** [comment]
I noticed that while the tooltip works, the position is off. My guess is that this has to do with the way reveal.js scales its slides. You can even see this in the demo.

**Comment by rajgoel** [comment]
Might be related to #20
