### ISSUE TITLE
In the animate plugin delay and duration seem to have no effect when clicking through presentation

### ISSUE THREAD

**Issue by GeorgRamer** [rajgoel/reveal.js-plugins#105]
I tried to use the the animate to animate an svg in a presentation. To my understanding, when clicking through the presentation, delay and duration should set how long the animation takes and how much it is delayed from the corresponding fragment showing up. However, transitions always seem to happen immediately and rapidly. 

Here is an example of code that is not working as expected:
```html
				<section>
				<p class="fragment fade-in-then-semi-out" >
								Content
						</p>	
						<p class="fragment fade-in-then-semi-out" >
								Content
						</p>	
						<p class="fragment fade-in-then-semi-out" >
								Content
						</p>	
						<p class="fragment fade-in-then-semi-out" >
								Content
						</p>	
						<p class="fragment fade-in-then-semi-out" >
								Content
						</p>
						<p class="fragment fade-in-then-semi-out" >
								Content
						</p>
				<div data-animate data-src="figures/test.svg">
<!--
{
"setup": [
],
"animation": [[],[
{
"element": "#everything",
"modifier": "opacity",
"parameters": [ 0]
}],[
{
"element": "#everything",
"modifier": "opacity",
"parameters": [ 1]
}
],
[
{
"element": "#circle",
"modifier": "delay",

"parameters": [200]
},
{
"element": "#circle",
"modifier": "dmove",
"delay": 400,
"when": "now",
"duration" : 2000,
"parameters": [ [20,10]]
}
],
[
{
"element": "#everything",
"modifier": "opacity",
"parameters": [ 1 ]
}
],[]
]
}
-->
</div>
					</section>

```

**Comment by GeorgRamer** [comment]
Thank you for your reply. I assume this means the issue should be closed?

Also, thank you for providing these plugins!

**Comment by GeorgRamer** [comment]
As an ugly hack, I replaced `pause()` in line 297 in animate/plugin.js with `play()` to make it work for me for now.

**Comment by rajgoel** [comment]
I just added an option to automatically start animation when clicking through the slides 9c4a5deb71443bb73dbeb6b3d5d3206c0e244882. Didn't do much testing, but it might do the job for you. The only thing you need to do is to add
```js
Reveal.initialize({
	animate: {
		autoplay: true
	}
});
```
in your presentation. Let me know if you experience any issues.

**Comment by GeorgRamer** [comment]
Thank you! It works now!
