### ISSUE TITLE
please consider hosting package on cdn

### ISSUE THREAD

**Issue by malmarz** [rajgoel/reveal.js-plugins#106]
menu package seems to be hosted, but the chalkboard is not working when I used jsdelivr GitHub project cdn.

I keep getting the following error on my site:

`(index):146 Uncaught ReferenceError: toggleNotesCanvas is not defined`

even though the chalkboard button shows up on my reveal slides.

I can only get checkerboard to work if it is hosted on my website. But we need it hosted on a CDN so we can incorporate in https://wowchemy.com/
\

**Comment by rajgoel** [comment]
Can you provide an easy instruction on how to do so? Don't have any experience in this.

**Comment by Doko-Demo-Doa** [comment]
Well, you can create a PR, according to [this](https://stackoverflow.com/questions/44981404/how-do-i-upload-to-cdnjs).

**Comment by edemaine** [comment]
This package is already published to NPM, so it's available via NPM-based CDNs, e.g. https://cdn.jsdelivr.net/npm/reveal.js-plugins@latest/
