### ISSUE TITLE
Chalkboard plugin --> Change color on touch devices

### ISSUE THREAD

**Issue by a-i-m-a-r** [rajgoel/reveal.js-plugins#115]
Hi,
The chalkboard plugin is essential in my presentations. However I use a touch device (without keyboard) and although there are some buttons implemented to draw on the slides or on a chalkboard/whiteboard I miss a button to change the color. So I made a few changes on the plugin.js file that you may wish to add. I would do a pull request but I have never done it, so I do not feel very confident.

- Just link the button with the function:

`    toggleColor: function() { colorNext(); },`

- Specify if it is shown:

`	var toggleColor = true;`

- And create a button similar to the ones already implemented:

```
if ( toggleColor ) {
//console.log("toggleColor")
		var button = document.createElement( 'div' );
		button.className = "chalkboard-button";
		button.id = "toggle-color";
		button.style.visibility = "visible";
		button.style.position = "absolute";
		button.style.zIndex = 30;
		button.style.fontSize = "24px";

		button.style.left = toggleColor.left || "180px";
		button.style.bottom = toggleColor.bottom ||  "30px";
		button.style.top = toggleColor.top ||  "auto";
		button.style.right = toggleColor.right ||  "auto";

		button.innerHTML = '<a href="#" onclick="RevealChalkboard.toggleColor(); return false;"><i class="fa fa-plus"></i></a>'
		document.querySelector(".reveal").appendChild( button );
	}
```

**Comment by a-i-m-a-r** [comment]
Even better, if the button to change the color would only be visible once you are in drawing mode (chalkboard or on the slides), and hide when you return to navigation mode. So far, I was not able to achieve this, so I have no proposals.

**Comment by rajgoel** [comment]
Yes, that would be nice: a `div` with color buttons that is shown/hidden when toggling the drawing canvas. This is in fact on my wish list, but haven't found time to do so myself.

**Comment by a-i-m-a-r** [comment]
I prefer to keep it minimalistic, just one button, even though I have to click the button several times to achieve a desired color. Personally I do not mind which color I use each time, just to be able to change them is enough to make contrast. But I suppose that the way to achieve it, would be similar in both cases.

**Comment by a-i-m-a-r** [comment]
Including the following in **function showChalkboard ()**
`		if ( toggleColor ) {
			var button =  document.getElementById("toggle-color");
			button.style.visibility = "visible";
		}`
the button to change colours shows, and including the following in **function closeChalkboard ()**
`		if ( toggleColor ) {
			var button =  document.getElementById("toggle-color");
			button.style.visibility = "hidden";
		}`
hides it.
I could not make it show when drawing on the slides. 
I will follow trying.

Disclaimer: I am not developer, so my code may not be the best.

**Comment by a-i-m-a-r** [comment]
Hi there,
I manage to make it work also when drawing on the slides. I have inserted the same code mentioned in the previous message, but this time in **function toggleNotesCanvas()**. For better coherence with the rest of the buttons, I changed "toggleColor" by "toggleColorButton", "toogle-color" id, by "color-button", etc. Finally all looks like this:

the button calls coloNext(function), to change the colors.

```
	toggleColor: function() { colorNext(); },
````
Activates the button
```
        var toggleColorButton = true;
````
Configures the button. Initially it is not visible. You can change the icon to whatever you want.
```
		if ( toggleColorButton ) {
//console.log("toggleColorButton")
		var button = document.createElement( 'div' );
		button.className = "chalkboard-button";
		button.id = "color-button";
		button.style.visibility = "hidden";
		button.style.position = "absolute";
		button.style.zIndex = 30;
		button.style.fontSize = "24px";

		button.style.left = toggleColorButton.left || "180px";
		button.style.bottom = toggleColorButton.bottom ||  "30px";
		button.style.top = toggleColorButton.top ||  "auto";
		button.style.right = toggleColorButton.right ||  "auto";

		button.innerHTML = '<a href="#" onclick="RevealChalkboard.toggleColor(); return false;"><i class="fa fa-plus"></i></a>'
		document.querySelector(".reveal").appendChild( button );
	}
````
When showChalkboard() function is called, the button is made visible.
```
	function showChalkboard() {
//console.log("showChalkboard");
		clearTimeout(touchTimeout);
		touchTimeout = null;
		drawingCanvas[0].sponge.style.visibility = "hidden"; // make sure that the sponge from touch events is hidden
		drawingCanvas[1].sponge.style.visibility = "hidden"; // make sure that the sponge from touch events is hidden
		drawingCanvas[1].container.style.opacity = 1;
		drawingCanvas[1].container.style.visibility = 'visible';
		mode = 1;
		// broadcast
		var message = new CustomEvent('send');
		message.content = { sender: 'chalkboard-plugin', type: 'showChalkboard' };
		document.dispatchEvent( message );
		if ( toggleColorButton ) {
			var button =  document.getElementById("color-button");
			button.style.visibility = "visible";
		}
	}
````
When closeChalkboard() function is called, the button is hidden.
```
	/**
	 * Closes open chalkboard.
	 */
	function closeChalkboard() {
		clearTimeout(touchTimeout);
		touchTimeout = null;
		drawingCanvas[0].sponge.style.visibility = "hidden"; // make sure that the sponge from touch events is hidden
		drawingCanvas[1].sponge.style.visibility = "hidden"; // make sure that the sponge from touch events is hidden
		drawingCanvas[1].container.style.opacity = 0;
		drawingCanvas[1].container.style.visibility = 'hidden';
		xLast = null;
		yLast = null;
		event = null;
		mode = 0;
		// broadcast
		var message = new CustomEvent('send');
		message.content = { sender: 'chalkboard-plugin', type: 'closeChalkboard' };
		document.dispatchEvent( message );
		if ( toggleColorButton ) {
			var button =  document.getElementById("color-button");
			button.style.visibility = "hidden";
		}
	}
````
When toogleNotesCanvas() function is called, the button is made visible if the notes canvas is made visible, otherwise it is hidden.
```
    	function toggleNotesCanvas() {
		if ( !readOnly ) {
			if ( mode == 1 ) {
				toggleChalkboard();
				notescanvas.style.background = background[0]; //'rgba(255,0,0,0.5)';
				notescanvas.style.pointerEvents = "auto";
			}
			else {
				if ( notescanvas.style.pointerEvents != "none" ) {
					event = null;
					notescanvas.style.background = 'rgba(0,0,0,0)';
					notescanvas.style.pointerEvents = "none";
							if ( toggleColorButton ) {
								var button =  document.getElementById("color-button");
								button.style.visibility = "hidden";
							}
				}
				else {
					setColor(0);
					recordEvent( { type:"setcolor", index: 0, begin: Date.now() - slideStart } );
					if (color[mode]) {
//						let idx = color[mode];
						var idx = color[mode];
						setColor(idx);
						recordEvent( { type:"setcolor", index: idx, begin: Date.now() - slideStart } );
					} else {
						color[mode] = 0;
					}
					notescanvas.style.background = background[0]; //'rgba(255,0,0,0.5)';
					notescanvas.style.pointerEvents = "auto";
							if ( toggleColorButton ) {
								var button =  document.getElementById("color-button");
								button.style.visibility = "visible";
							}
				}
			}
		}
	};
```
I think that this is a good approach to implement your idea of a `div` with color buttons.

**Comment by rajgoel** [comment]
@a-i-m-a-r Motivated by your input I finally added a color picker that shows when the drawing canvas is toggled. See https://rajgoel.github.io/reveal.js-demos/chalkboard-demo.html
