### ISSUE TITLE
NPM release old?

### ISSUE THREAD

**Issue by edemaine** [rajgoel/reveal.js-plugins#121]
I noticed that `chalkboard/palette.css` is not in the NPM release, and neither is the associated `colorButtons` code in `chalkboardp/plugin.js`. Probably just need to do another `npm publish`.

**Comment by rajgoel** [comment]
That's right. I am just wrapping up some stuff before the next release (which will include chalkboard broadcasting, polls, Q&As).

Your latest comments come in handy. Thanks a lot!

**Comment by rajgoel** [comment]
P.S. For consistency with other plugins I renamed `palette.css`to `style.css`.

**Comment by edemaine** [comment]
@rajgoel Very cool!! Finally got a chance to try out the demo (sorry for the long delay). I couldn't figure out a way to get two hosts hosting/drawing on the same slides, even though the [sample code](https://github.com/rajgoel/reveal.js-demos/blob/dff5521f3200ae94527fa20cef965008d2a2aa06/seminar-demo.html#L255-L258) seems to open the same room in the case of multiple hosts &mdash; or am I missing something? I have an upcoming presentation with multiple speakers for which this would be nice.

P.S. [Here's a talk](https://github.com/edemaine/talk-token-swapping-in-trees/) that features the Chalkboard plugin. I'm also working on a [template repo](https://github.com/edemaine/reveal-pug-talk) for this combination of technologies, which I'm becoming quite fond of.

P.P.S. I assume you've seen [Cocreate](https://github.com/edemaine/cocreate)?

**Comment by rajgoel** [comment]
@edemaine Do you have the problem using the demo on https://rajgoel.github.io/reveal.js-demos/seminar-demo.html ? If so, the only important thing to consider should be that the room name is the same. You can set the room name with an URL parameter, e.g. https://rajgoel.github.io/reveal.js-demos/seminar-demo.html?room=MY_ROOM_NAME. Every instance should automatically connect to this room and any host should send slide change events and chalkboard drawings. I just tested an it works for me. Let me know if it doesn't for you and any details that may help me identifying the issue.

![Seminar](https://user-images.githubusercontent.com/4448455/128643496-ee8da797-cc9a-4136-b8ce-380c86ba1650.gif) 

P.S. Didn't know about `Cocreate`, but it looks interesting.

**Comment by edemaine** [comment]
Ohh, the room name feature is what I was missing. I was trying the "host seminar" button without fixing a room name, which I guess ended up generating a random room name, I guess on [this line](https://github.com/rajgoel/reveal.js-demos/blob/dff5521f3200ae94527fa20cef965008d2a2aa06/seminar-demo.html#L198). Makes sense now, and works for me.

It might be worth adding some documentation to the demo to explain this feature. In this example, we could simply mention that once a client joins they can also become a host using the "host seminar" button (because they have the password). I'll make an issue.
