### ISSUE TITLE
[chalkboard] Vertical shift in chalkboard drawings 

### ISSUE THREAD

**Issue by rajgoel** [rajgoel/reveal.js-plugins#124]
As initially reported in https://github.com/rajgoel/reveal.js-plugins/issues/104#issuecomment-881256803, chalkboard drawings may have a vertical shift. An example, showing this behaviour is found at [here](https://farberg.de/reveal-test/).

**Comment by rajgoel** [comment]
@pfisterer  I can see the issue, but I am not sure where it comes from. Possible causes could be `margin`, `maxScale`, `minScale` options, or an HTML-object that causes the vertical shift. I see two options to systematically find the initial cause: a) remove as many  configurations and other plugins, b) to adapt the demo step by step to fulfill your needs. In either case this might find the exact point where the issues occurs first. With that information I could identify whether this is a bug that needs to be fixed, or a possible limitation that should be documented.

**Comment by pfisterer** [comment]
@rajgoel I tried removing everything and added `width: 960, height: 700,  margin: 0.04,  minScale: 0.2,  maxScale: 2.0` as suggested in the other thread. However, it still shows this vertical offset. I've also replaced my custom theme with the `simple' one provided by reveal.js. So, option a.) suggested by you wasn't successful yet...

**Comment by pfisterer** [comment]
I compared your demo with mine line by line and obviously, `node_modules/reveal.js-plugins/chalkboard/style.css` was missing in my presentation. However, in previous versions, this worked without issues. Thanks for your support.

Another thing that is odd, is that (apart from the look and feel), I cannot select a colour. Clicking on, e.g., `red` gives me the following error:

<img width="1020" alt="image" src="https://user-images.githubusercontent.com/302635/125932730-7eb11246-d9fd-48ad-8237-b5aa4438f3bb.png">

**Comment by rajgoel** [comment]
Glad to hear that the shift issue is resolved. The color picker functionality looks like a bug and I have an idea for a fix. Changing the color by pressing keys `X` and `Y` works.

**Comment by rajgoel** [comment]
Could you please check by modifying the chalkboard plugin at line 254:
```js
			colorButton.addEventListener("click", function(e) {
console.log(e.target.parentElement.outerHTML); // INSERT THIS LINE
				colorIndex(e.target.parentElement.getAttribute("data-color"));
			});
```
and let me know what is printed to the console.

**Comment by pfisterer** [comment]
Ok, I've updated [my test-presentation](https://farberg.de/reveal-test/index.html) and clicking on a color yields:

```html
<ul><li data-color="0" style="color: rgb(100, 100, 100);">
<i class="fa fa-square"></i></li><li data-color="1" style="color: rgb(30, 144, 255);">
<i class="fa fa-square"></i></li><li data-color="2" style="color: rgb(220, 20, 60);">
<i class="fa fa-square"></i></li><li data-color="3" style="color: rgb(50, 205, 50);">
<i class="fa fa-square"></i></li><li data-color="4" style="color: rgb(255, 140, 0);">
<i class="fa fa-square"></i></li><li data-color="5" style="color: rgb(150, 0, 255);">
<i class="fa fa-square"></i></li><li data-color="6" style="color: rgb(255, 220, 0);">
<i class="fa fa-square"></i></li></ul>
```

followed by this error message:

```console
plugin.js:893 Uncaught TypeError: Cannot read property 'cursor' of undefined
    at setColor (plugin.js:893)
    at colorIndex (plugin.js:1716)
    at HTMLLIElement.<anonymous> (plugin.js:255)

```

**Comment by rajgoel** [comment]
Perfect, that's what I assumed. Could you check replacing the part by
```
			colorButton.addEventListener("click", function(e) {
				var element = e.target;
				while ( !element.hasAttribute("data-color")) {
					element = element.parentElement;
				}
				colorIndex(element.getAttribute("data-color"));
			});
```
I believe that should be the fix and upon confirmation I can do an update.

**Comment by rajgoel** [comment]
Btw. the reason for the `<i class="fa fa-square"></i>` not showing properly as box are likely due to fontawesome missing.

**Comment by pfisterer** [comment]
Perfect, now it works! Thank you!

**Comment by rajgoel** [comment]
Thanks for reporting and testing!
