### ISSUE TITLE
Use print-pdf to export animated SVG to PDF

### ISSUE THREAD

**Issue by lechten** [rajgoel/reveal.js-plugins#125]
Hi there,

many thanks your great plugins!

I use the anything plugin to show SVG figures in multiple steps. When printing to PDF with parameter `print-pdf` of reveal.js, only the initial state is shown. You can see the same behavior with the Petri net in the [Anything demo](https://rajgoel.github.io/reveal.js-demos/anything-demo.html). The red dot does not appear (by default, 6 identical slides are produced). Is there an easy way to export the final state to PDF?

Thanks
Jens

**Comment by rajgoel** [comment]
@lechten The `anything` plugin doesn't have any out-of-the-box functionality in manipulating PDF printouts. Your use case looks like a perfect match for the `animate` plugin which creates PDF pages for each fragment. Please reopen this issue should there be any issues with the `animate` plugin.

**Comment by Mewiss** [comment]
I can't see images in the print--pdf view when I add them with the animate pluggin. How can I solve it?
