### ISSUE TITLE
Seminar documentation: Doesn't work with file: URLs

### ISSUE THREAD

**Issue by edemaine** [rajgoel/reveal.js-plugins#129]
Small thing that confused me for a bit: As far as I can tell, the seminar plugin (or the public socket.io server) doesn't support `file:` URLs for local testing.  (I got the error message "No venue provided" from the server, I believe.)  Once I deployed to GitHub Pages with an `https` protocol, everything worked fine.  https://github.com/rajgoel/reveal.js-plugins/blob/master/seminar/README.md should ideally be updated to mention which protocols work.  (Does `http` work? I didn't test.)

**Comment by rajgoel** [comment]
For testing the demo can now be run from https://rajgoel.github.io/reveal.js-demos/?topic=seminar with a seminar server installed on localhost
