### ISSUE TITLE
Toggle notes canvas to hide notes also

### ISSUE THREAD

**Issue by vfonsecad** [rajgoel/reveal.js-plugins#130]
Hi, is there a way to hide also the notes when toggling the notes canvas? Thanks!

**Comment by rajgoel** [comment]
There is no such feature at the moment (you can only clear notes).

**Comment by vfonsecad** [comment]
This functionality is available with this plugin https://github.com/satoshifuku/handwriting so I thought it could be possible here also. Thanks for the fast answer!
