### ISSUE TITLE
[anything] Random numbers in a looping slideshow?

### ISSUE THREAD

**Issue by Alex-Jongman** [rajgoel/reveal.js-plugins#132]
The random example works. 
But because the initialize function will only be executed once at the beginning of the slide show, the page with the random number will always show the same number if the slideshow is looping.
Is there a way to generate a random number each time the slide is shown in a looping slideshow?

**Comment by rajgoel** [comment]
The anything-plugin does not support this kind of use case. The easiest should be to create your own plugin with event listener, where you create your random numbers:

```js
Reveal.addEventListener( 'slidechanged', function( event ) {
// update random number
});
```
