### ISSUE TITLE
load CSV file on Chart.js

### ISSUE THREAD

**Issue by a-i-m-a-r** [rajgoel/reveal.js-plugins#137]
Although the README file from "chart" plugin states that is possible to load data from a csv file, I cannot make it work.

> The CSV file is expected to only contain data values

The examples of the demo have the data written in the code (with some header text also), thus not loading from a real csv file. The csv file should not have these headers? I suppose the data must be separated by commas. Must it be an array (I mean with square brackets and all)?

**Comment by rajgoel** [comment]
Hi, 

there is an example here: https://rajgoel.github.io/reveal.js-demos/chart-demo.html#/0/4
the file loaded is this: https://rajgoel.github.io/reveal.js-demos/chart/data.csv

Hope this helps.
