### ISSUE TITLE
[Chalkboard] eraser on mobile device browser

### ISSUE THREAD

**Issue by xieby1** [rajgoel/reveal.js-plugins#149]
Long press to activate the eraser does not work on several mobile device browsers.

Tested on Android 10

* ❌ Chrome 102.0.5005.78
* ❌ Edge 102.0.1245.39
* ❌ Kiwi 101.0.4951.40
* ✅ Firefox 98.3.0

I tried to move `touchstart` event handler code to `mousedown`, but it does not work.

Does anyone have ideas to solve this problem?

**Comment by rajgoel** [comment]
Removed unreliable long press and instead added sponge to palette in v4.2.2
