### ISSUE TITLE
[Chalkboard] Can chalkboard made to work in replay mode when building a self-contained HTML?

### ISSUE THREAD

**Issue by TS-CUBED** [rajgoel/reveal.js-plugins#152]
I use the chalkboard a lot in teaching. This works great if the slide-deck is created as `slides.html` and a directory `slides_files`, which contains all the audio/drawings. 

But I need to supply files on the VLE (Virtual Learning Environment), so have to be able to make a self-contined HTML.

This works for everything but the chalkboard. Is it possible to make the "replay" function work with self-contained HTML files?

**Comment by rajgoel** [comment]
The replay function requires a JSON file to be loaded which cannot easily be embedded within the HTML.
