### ISSUE TITLE
[chalkboard] when using a pen the last part of a line is erased when lifting the pen

### ISSUE THREAD

**Issue by mgmgmg** [rajgoel/reveal.js-plugins#156]
Moving the pen above the screen seems to switch the pen behavior to "erasing". This means that the end of each line is erased as soon as  I lift the pen which is undesired. The "touch" behavior in contrast works correctly, lifting the finger does not activate erasing.

**Comment by psteinb** [comment]
The chalkboard plugin is a totally awesome addition to reveal.js.

In general, from my experience (Samsung Galaxy S7 and pen, iphone, Fairphone) it is quite tricky to toggle editing/erasing modes given touch gestures only. It would be great to have a button for the eraser. On mobile devices during a presentation, sending a del command or a right-mouse click can be quite tricky.

**Comment by rajgoel** [comment]
The eraser function is changed in v4.2.2 and is no longer initiated by long press. Instead you can now find a sponge in the palette. Probably the erasing of the last part is no longer happening.
