### ISSUE TITLE
[chalkboard] [customcontrols] TypeError: config.controls is undefined in initCustomControls plugin.js:46

### ISSUE THREAD

**Issue by lechten** [rajgoel/reveal.js-plugins#158]
The README for the Chalkboard plugin instructs to include the customcontrols plugin. That leads to:

```
Uncaught (in promise) TypeError: config.controls is undefined  (in initCustomControls plugin.js:46)
```

In a [previous version](https://github.com/rajgoel/reveal.js-plugins/blob/f3964a8fbfc37adc6120b2b287900a710ef8e830/customcontrols/plugin.js), customcontrols defined `controls` in its `config`, which it does not do any more since commit 5c6c8a4019e704d59ebe0364fe311632a64523e2. What is the recommended way to use the Chalkboard plugin?

**Comment by rajgoel** [comment]
@lechten for quick help you might want to look at the code of this presentation: https://talks.telematique.eu/cbi2022/

**Comment by lechten** [comment]
Many thanks!

**Comment by murilo-cunha** [comment]
Had a similar issue. Ended up partially reverting the commit to have

```js
var config = Reveal.getConfig().customcontrols || {
    controls: [],
  };
```
Is there a better way?

>  for quick help you might want to look at the code of this presentation: https://talks.telematique.eu/cbi2022/

How can I find the code for the presentation?

(Also changed the font-wesome link from [this ](https://github.com/rajgoel/reveal.js-plugins/blob/master/chalkboard/README.md?plain=1#L43) to `<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"/>`)

**Comment by rajgoel** [comment]
I have modernized the demos that can be used for an example setup
