### ISSUE TITLE
Audio doesn't play on IOS

### ISSUE THREAD

**Issue by anctr** [rajgoel/reveal.js-plugins#166]
Trying out the demo - clicking on the play icon on the audio player, there is no sound in IOS. I have tried on iPhone and iPad. Both chrome and safari exhibit the same behavior

**Comment by rajgoel** [comment]
The demos are modernised (but there are no audio recordings on most slides). 

On https://rajgoel.github.io/reveal.js-demos/#1/1/?topic=audio-slideshow the demo should play audio for the first fragment (i.e. when "Listen to the birds" is shown).

Please reopen if the problem persists.
