### ISSUE TITLE
"Questions" plugin

### ISSUE THREAD

**Issue by a-i-m-a-r** [rajgoel/reveal.js-plugins#167]
Is there any possibility to detach the "Questions" plugin from the seminar plugin?
I would love to provide the audience an opportunity to make questions (and upvote them), but I am not interested in the seminar plugin or any Multiplex plugin. They are great tools when you are presenting online, but whe you are face to face I prefer them to look at me.
I already use the ["poll" plugin from Johannes](https://github.com/jschildgen/reveal.js-poll-plugin) and found very interesting to add the possibility of asking anonymous questions. I know the former is based on SQL and the latter relies on Socket.io, but is it feasible to detach it?

**Comment by rajgoel** [comment]
The questions-plugin requires the seminar-plugin as it doesn't implement communication itself. This is a technical requirement.

Just to understand your issue. You want to use the questions-plugin without synchronization of slides provided by the seminar-plugin? If this is what you want, it could be an idea to provide an option in the seminar-plugin to turn-off slide synchronization. But does that make sense? The audience might be on the wrong slide ...

**Comment by a-i-m-a-r** [comment]
All right. If the communication is only established by the seminar plugin, my request does not make sense. The question plugin is very good, though. I like it very much.
My approach does not need multiplex since I pretend the audience to be focused on me, my screen projection and my gestures. They can know which is the right slide looking at me. Even in an online presentation I can share my screen so the audience can check which is the slide I am projecting. But they will be free to go back and forth in case they want/need to find/remember some info piece.
Thank you for the clarification.
