### ISSUE TITLE
Charts completely broken

### ISSUE THREAD

**Issue by nbarnwell** [rajgoel/reveal.js-plugins#175]
Tested in Chrome and Edge. Chart appears briefly, very slowly animated, getting bigger and bigger then bang - white box with a sad face.

I took the minimal.html file and put the example code in from the documentation: https://jsfiddle.net/mgb5tea1/1/

**Comment by rajgoel** [comment]
It is not completely broken and works fine in the demo: https://rajgoel.github.io/reveal.js-demos/?topic=chart

Please reopen with a less offensive title.

**Comment by nbarnwell** [comment]
Fair enough, I'll change the title. The demo is the first place I went. However, the demo demonstrates some other things that make it hard to directly compare with the basic version I posted to find what I've done wrong.

**Comment by rajgoel** [comment]
Will take a look at this as soon as I find time. One possible cause could be related to the updates in the most recent reveal.js version. Using an older reveal.js version would be one thing to try.

**Comment by fuhrmanator** [comment]
Wrapping the `<canvas>` with a `<div style="height:480px">` (of a fixed height) will prevent this bug. 

I think I changed the fiddle: https://jsfiddle.net/5g0pf1r9/
