### ISSUE TITLE
Chalkboard does not cooperate with zoom

### ISSUE THREAD

**Issue by axiomtutor** [rajgoel/reveal.js-plugins#176]
Hi, I want to thank you for the super-cool plugins!  I'm just discovering them and starting to incorporate some of them.

But about the bug: when I use the RevealJS feature to zoom into a portion of the screen by Alt+click on a place in the presentation, if I then also open the notes panel and try to start drawing, it doesn't draw where my cursor is.  It seems to not register that the zoom has caused a change of coordinates for the mouse events.  

I'm not sure whether this is something you can handle on your end or if you need the maintainer of the zoom feature to help the notes feature to cooperate.  But if you ever get this resolved it would be great for me!

(In the mean time, I know that I can use the work-around of just using external software to do the zooming and screen writing.  It just would make things so much more convenient if it all happened inside RevealJS.)

Thanks again!

**Comment by rajgoel** [comment]
Interoperability of different plugins is quite challenging. Also aligning the notes canvas with the slide content is nontrivial to work with different screen sizes. Thus, a fix for this will likely never be implemented.

**Comment by axiomtutor** [comment]
> Interoperability of different plugins is quite challenging. Also aligning the notes canvas with the slide content is nontrivial to work with different screen sizes. Thus, a fix for this will likely never be implemented.

Yep, that's what I pretty much expected, and totally reasonable. 

Thanks again for the chalkboard, it's still super cool! :)
