### ISSUE TITLE
Problem with Smooth Audio Transition Across Slides

### ISSUE THREAD

**Issue by mohsenBanan** [rajgoel/reveal.js-plugins#177]
I want to play a music sound track across several slides.
With ffmpeg I split the music file into say 7 second segments.
I then assign each segment to a slide. When I auto play, the audio is not smooth across slide transitions. 
With mplayer I play the same segments sequentially and audio is perfectly smooth.
Is this because reveal audio player does a stop and start across slide transitions?
Are there some options that I have overlooked?
Can this be fixed?
I would consider this a common use-case but my searches did not end in a solution.
Thanks in advance.

**Comment by rajgoel** [comment]
I doubt that the current architecture works for your use case. Each slide has its own media player element and when switching between slides the player is changed. This is not seamless.

For your use case, it probably would be best to have one player element with the full audio. When slides are changed in sequence nothing needs to be done. When jumping to another slide on could seek to the respective timestamp (similar to how video controls and audio controls can be synchronised already). This, however, is out of scope of the plugin.
