### ISSUE TITLE
[anything] Help extending anything to parse a Google Doc

### ISSUE THREAD

**Issue by gooddadmike** [rajgoel/reveal.js-plugins#18]
I am hoping to have a google spreadsheet connected to my presentation so that when a new row is added (maybe from a google form even) it would generate a new slide.

```
<section>
    <h1><!--column 1--></h1>
    <span><!--column 2--></span>
</section>
```

and the table would look like this:

| Full Name | Pitch Title |
| --- | --- |
| Mable Daniel | Modal Flux Duractor |
| Harvey Chandler | Pre-famulated Amulite |

Any nudges on how to start?

**Comment by rajgoel** [comment]
Looks like your use case requires several things to be implemented:

1. Adding slides dynamically (see https://github.com/hakimel/reveal.js/issues/1301)
2. Synching content with the google sheet (Not sure how this can be done. Maybe you find something here https://developers.google.com/sheets/)
3. Showing the spreadsheet in your slidedeck (see http://courses.telematique.eu/reveal.js-plugins/spreadsheet-demo.html)

Alternatively you could simply insert the the sheet in an iframe (see http://courses.telematique.eu/reveal.js-plugins/fullscreen-demo.html#/3/1)

**Comment by getthemike** [comment]
Thanks. These are helpful suggestions. I won't need to expose data in table
form. I'll just need a parser to generate an h1 or a span tag depending on
the column name (for v1 at least). Of course I'll share whatever I come up
with.

**Comment by rajgoel** [comment]
This https://github.com/jsoma/tabletop might be helpful

**Comment by getthemike** [comment]
I'll think I will publish a plugin that uses this. Got a mostly working demo. Problem is updating the gsheet while in the row-driven slide causes you to have to refresh and tosses you back to slide 1. But it's coming along nicely.
