### ISSUE TITLE
Help on controlling SVG fragments

### ISSUE THREAD

**Issue by egrosclaude** [rajgoel/reveal.js-plugins#21]
No JS programmer here, please bear with me. I'm struggling to integrate Snap (http://snapsvg.io) into reveal.js.  using Anything, I can insert Snap scripts to create SVG into Reveal slides. I can define fragments inside SVGs, and Reveal responds as expected showing or hiding these upon the event: 

```
<section>
<div id="myid" class="snapsvg" width="100%" height="100%">
        <svg viewBox="0 0 600 400" width="100%" height="100%"></svg>
        <!--
        {
                "initialize" : "function(container) {
                        var svg = Snap('#myid svg');
                        var rect = svg.rect(20,20,50,60,2);
                        rect.addClass('fragment');
                }"
        }
        -->
</div>
</section>

...
{className: "snapsvg", initialize: (function(container, options) { if(options && options.initialize {options.initialize(container)} }) },
...
```
Now, I would like Snap SVG animations to be driven by the usual fragment workflow like Anything  does for 'animate' class. I'd like to write my own JS+Snap functions and set them as callbacks to 'fragmentshown' or 'fragmenthidden' events. I was thinking of something along the lines of:

```
<!--
  {
      "initialize" : "function(container) {
              var svg = Snap('#myid svg');
              var rect = svg.rect(20,20,50,60,2);
              rect.addClass('fragment');
              var shownFn = function(){ /* some animation or whatever */ };
              rect.attr({ shown: shownFn });
         }"
 }
 -->

{className: "snapsvg",
       initialize: (function(container, options) {
             if(options && options.initialize) { options.initialize(container) }
             Reveal.addEventListener('fragmentshown', function(event) {
                             if(event.fragment.getAttribute('shown')) {
                                     var callback = event.fragment.getAttribute('shown');
                                     callback();
                             }
                      });
       })
 },

```
And similarly for 'fragmenthidden'. Now, this won't work, as the type of callback is string. I assume (one) problem is that I can't get JSON to hold a function value for a key. The closer I have been to success is by defining just a string of code in showFn and then making var callback a function by means of new Function(). However, this feels overly contrived and lets any syntax errors to lurk until the callback invocation. Is there any sane way of going about this?

**Comment by rajgoel** [comment]
Hi, does it work now for you?

**Comment by egrosclaude** [comment]
Hi, thank you for answering - after some further thought I found that I still had a lot to learn about Snap.svg and that I probably was too keyboard-happy in asking this question. 

Later I realized that visible SVG elements are not suitable Reveal fragments. Transforms should be fragments instead (à la animate). 

Still scratching my head... Sorry for the noise :(
