### ISSUE TITLE
Audio file not supported in Windows ?

### ISSUE THREAD

**Issue by maxMidius** [rajgoel/reveal.js-plugins#22]
Is this plugin not supposed to work on Chrome on a windows box ?  Looks like the audio file format is not supported. Am I missing something obvious ?

**Comment by rajgoel** [comment]
All plugins should work on Chrome. Could you please provide some more detail. Are you referring to  audio-slideshow.js or slideshow-recorder.js? What have you tried? What is happening? Which version of Chrome are you using? Are you sure your internet connection is fine (audio may need some time before it is loaded)?

**Comment by maxMidius** [comment]
OK - let me restate my goals and findings 
1. I tested your main demo (with jungle birds etc) 
        *  on Ubuntu / Chrome   -->  works
        *  on  Windows / IE         -->  does not work  
        *  on  Windows / Chrome  -->  works    
        *  on my office windows / Chrome via  CITRIX remote login  --->   Does not work

I have to try this locally on my office Windows/Chrome combo tomorrow to understand why it does not work - This will help me get to the bottom of the real issue - and then I can use your expertise and insights.  Until then  thanks a lot for responding to my SOS  ( that was my bad - i was using IE not Chrome)

**Comment by rajgoel** [comment]
Closing this issue as IE is not supported and remote login is probably causing the problem.
