### ISSUE TITLE
[chart] Charts not respecting aspect ratio after update to 2.5

### ISSUE THREAD

**Issue by alessandrogreco10** [rajgoel/reveal.js-plugins#28]
Charts seems now unable to respect aspect ratio (modifying aspect ratio option won't work) and are currently drawn in an incorrect way.
They were visualized correctly in 2.3 now they are not anymore.

If page is reloaded then the chart is visualized correctly, I think the problem is related then to slidechange redraw function.
 Wrong pic shows chart before reload and Correct shows after reload chart
<img width="1149" alt="wrong" src="https://cloud.githubusercontent.com/assets/27502576/25312198/8544475c-2813-11e7-9ba5-2dc5a7066973.png">
<img width="1068" alt="correct" src="https://cloud.githubusercontent.com/assets/27502576/25312200/8fc98eda-2813-11e7-83da-a339c3695397.png">

**Comment by rajgoel** [comment]
Hi,
thanks for reporting. No idea what is causing this behaviour. It don't think this is related to the slidechange because all charts are drawn upon loading (and reveal.js just shows hidden slides upon a slidechange). I assume that this is related to Chart.js and not the plugin itself. You might want to look for a solution there.

**Comment by alessandrogreco10** [comment]
Hi,
Thanks for your kind reply.
I found a work around simply avoiding the use of markdown in the same slide of chart.js canvas.
Still the aspect ratio bug related to the joint use of chart.js and markdown is something limited to piecharts and doughnuts (bars work strangely fine).
I also kept experiencing the mouse coordinate in fullscreen mode on both chrome and safari(just to mention it).

Thanks again for your help;

⁣Alessandro Greco​

**Comment by morckx** [comment]
Hi,

Has anyone found a solution? For me the issue isn't related to markdown, but seems to present every time with chrome (tested v59 and v63) also for bar charts, and also with Chart.js 2.7, however not at all with firefox.

A related issue is that tooltips are horizontally displaced.

See e.g. the plugin demo itself:

[https://rajgoel.github.io/reveal.js-demos/chart-demo.html#/0/4](https://rajgoel.github.io/reveal.js-demos/chart-demo.html#/0/4)

Thanks,
 Marc
