### ISSUE TITLE
Can I mix line and bar charts

### ISSUE THREAD

**Issue by RobinWPollard** [rajgoel/reveal.js-plugins#34]
Here is an example of what I want to do:

http://www.chartjs.org/samples/latest/charts/combo-bar-line.html

But so far I have failed to make it work. My config is the same as the getting started example here, except this for the actual chart:

```
<canvas data-chart="bar">
	<!-- 
	{ "data": {
		"labels": ["January"," February"," March"," April"," May"," June"," July"],
		"datasets": [
			{
				"type":"line",
				"data":[99,99,99,99,99,99,99],
				"label":"SLA Target",
				"backgroundColor":"rgba(20,220,220,.8)"
			},	
			{
				"type":"bar",
				"data":[100,100,99.5,100,100,100,100],
				"label":"Actual","backgroundColor":"rgba(220,120,120,.8)"
			}
		]
	}, 
	"options": { "responsive": true, "scales": { "xAxes": [{ "stacked": true }], "yAxes": [{ "stacked": true }] } } }
	-->
</canvas>
```
Is it possible or am I flogging a dead horse?

Thanks,
R.

**Comment by rajgoel** [comment]
I think this should be possible. Would be surprised if there is something in the plugin that makes it impossible.

**Comment by rajgoel** [comment]
Just tested your code as anew slide in the [demo](https://rajgoel.github.io/reveal.js-demos/chart-demo.html) and it works.
