### ISSUE TITLE
[audio-slideshow] Hiding the audio controls

### ISSUE THREAD

**Issue by jonesg504** [rajgoel/reveal.js-plugins#35]
The audio controls show for every slide regardless if the slide has audio. Is there any way to hide the audio controls for certain slides?

**Comment by rajgoel** [comment]
You can globally hide the player controls by setting the opacity value. However, the controls cannot be hidden depending on the existence of the audio. By default a silent audio of the given duration is generated to allow reveal.js to automatically advance after a certain amount of time while still allowing the user to pause auto sliding. Therefore, the controls are needed even if no audio file exits.

**Comment by lechten** [comment]
In my fork (PR #27) the player is hidden when no audio is present. See [here for a demo](https://oer.gitlab.io/OS/OS02-Interrupts.html).

**Comment by rajgoel** [comment]
Preliminary support as discussed in PR #27 is now available. However, a clean fix of this issue would be to check whether an audio file exists on the server. Unfortunately, this is nothing that I will be able to change soon due to time issues.
