### ISSUE TITLE
[Chart] Font size & color of labels and tooltips ignored

### ISSUE THREAD

**Issue by rugk** [rajgoel/reveal.js-plugins#38]
This is how I have set my config:
```js
chart: {
  defaults: { 
	  responsive: true,
		global: { 
			title: { fontColor: "#FFF" }, 
			tooltip: { bodyFontSize: 20, titleFontSize: 20, backgroundColor: "#FFF" }
		}, 
		legend: {
			display: true,
			labels: { fontColor: "#ff0000", fontSize: 20 }
		},
		scale: { 
			scaleLabel: { fontColor: "#FFF" }, 
			gridLines: { color: "#FFF", zeroLineColor: "#FFF" }, 
			ticks: { fontColor: "#FFF" }
		} 
	},
	line: { borderColor: [ "rgba(20,220,220,.8)" , "rgba(220,120,120,.8)", "rgba(20,120,220,.8)" ], "borderDash": [ [5,10], [0,0] ]}, 
	bar: { backgroundColor: [ "rgba(20,220,220,.8)" , "rgba(220,120,120,.8)", "rgba(20,120,220,.8)" ]}, 
	pie: { backgroundColor: [ ["rgba(0,0,0,.8)" , "rgba(220,20,20,.8)", "rgba(20,220,20,.8)", "rgba(220,220,20,.8)", "rgba(20,20,220,.8)"] ]},
	doughnut: { backgroundColor: [ ["rgba(0,0,0,.8)" , "rgba(220,20,20,.8)", "rgba(20,220,20,.8)", "rgba(220,220,20,.8)", "rgba(20,20,220,.8)"] ]},
	radar: { borderColor: [ "rgba(20,220,220,.8)" , "rgba(220,120,120,.8)", "rgba(20,120,220,.8)" ]}
}
```

I am showing a **doughnut** chart.

Especially the items under `legend.labels` (the font color and size) and the font size specified as `global.tooltip.titleFontSize` are ignored. Also `legend.display: false` is BTW ignored, if I set it, the label is always shown.

Firefox 56

Here a screenshot of the labels:
![grafik](https://user-images.githubusercontent.com/11966684/32018956-e3e1f3a0-b9cb-11e7-8bd2-5c48afcaa762.png)

And tooltip:
![toltip](https://user-images.githubusercontent.com/11966684/32019013-0ecfa1ac-b9cc-11e7-8d59-9dd4ddb0aa43.png)

**Comment by rugk** [comment]
Ah wait, I think I found the issue. `legend` and `scale` must be inside of `global`, right? If so, your Readme is, however, wrong… The indentation at exactly that position is strange anyway…

**Comment by rajgoel** [comment]
Updated Readme in  https://github.com/rajgoel/reveal.js-plugins/commit/8eb5d5b4f1f34bcaaaa7986798b6528f86445881
