### ISSUE TITLE
Attach multiple audio files to same slide.

### ISSUE THREAD

**Issue by umairm638** [rajgoel/reveal.js-plugins#42]
Hi there, I'm build slideshow of images in background and need to attach multiple audio (mp3) with same slide so that when one audio finish second one start playing automatically and so on, and when all audio attached to that slide completed it should move to next slide. I can attach one audio like below but don't know how to make it working with multiple audios.

    <section data-background="{{ asset('app') }}/{{ $photosRow->photoName }}" data-audio-src="<?php echo isset($audioArr[0]) ? $audioArr[0] : ''; ?>">
       <ul>
              <li>{{ $photosRow->photoDetails }}</li>
      </ul>
      </section>

**Comment by rajgoel** [comment]
You should be able to do this by using fragments, e.g. with an empty div (see https://rajgoel.github.io/reveal.js-demos/audio-slideshow-demo.html#/0/3)

**Comment by rajgoel** [comment]
Alternatively, you could of course also try to concatenate the audio files, I guess it should be easy to find tools for this.

**Comment by umairm638** [comment]
@rajgoel Thanks for your response, yeah I'm following that link for implementation which you provided. I've done something like this but it didn't played the second audio and also now it's not going to next slide but goes to first slide instead.

    <section data-background="http://localhost/familytree/public/app/photos/umDB3t4jtMZvR5F2NBazSVByf6zIVUhtNTRCjeAU.png" data-audio-src="http://localhost/familytree/public/app/audio/1510302571MyRecording (9).mp3">
         <ul>
             <li>this is my map.</li>
             <li>Photo Taken On 2017-11-01</li>
         </ul>
         <section id="fragments" data-audio-src="http://localhost/familytree/public/app/audio/1510302571MyRecording (9).mp3">
             <div></div>
          </section>
          <section id="fragments" data-audio-src="http://localhost/familytree/public/app/audio/1510305877MyRecording (7).mp3">
              <div></div>
          </section>
      </section>

**Comment by rajgoel** [comment]
Please carefully read the documentation for using fragment https://github.com/hakimel/reveal.js/#fragments or post your questions here: https://stackoverflow.com/questions/tagged/reveal.js
