### ISSUE TITLE
Audio controls not active when data-background-size is set

### ISSUE THREAD

**Issue by sascha2015** [rajgoel/reveal.js-plugins#44]
If section contains background-image and background-size the audio controls are visible but can not be clicked. Normaly on hover the controls get Opacity 1.0 and you can use them.
You can reproduce it just adding "background-size='100%' " in the section code.

section data-background-image='/media/tutorials/TUT1_de_slide20_img_portal.png' data-background-size='100%' data-audio-src='/media/tutorials/TUT1_de_slide20_frag_2.mp3'

other settings:
Reveal.initialize({
    transition: 'none',
    audio: {
        prefix: '/media/tutorials/',
        suffix: '.mp3',
        autoplay: true,
        defaultDuration: 0,
        playerOpacity: 0.05,
        playerStyle: 'position: fixed; bottom: 10px; left: 25%; width: 50%; height:60px; z-index: 33;',
    },});

**Comment by rajgoel** [comment]
Please reopen with a link to a sample - slidedeck showing the issue, if the issue is still relevant. Haven't had any issues with background images yet.
