### ISSUE TITLE
Broadcasting using a different system

### ISSUE THREAD

**Issue by netflakes** [rajgoel/reveal.js-plugins#45]
Hi there,
I am building an Elixir & Phoenix app using Reveal js for presentations and currently synching slide change events via phoenix sockets - am keen to get the Chalkboard to work with this as well - I have built some JS to intercept the events that start and stop drawing so I can pass data packets with drawing coordinates - I am sending this to each client and the JS in the clients is receiving them - but I am unsure which events to correctly fire - I have reviewed the code in lines 530 - 590... in debug mode I can see that the draw segment event is fired - but I think I must be missing some data in the content of the event as nothing is drawn on the screen.. Any advice from your end would be greatly appreciated - THANKS

**Comment by rajgoel** [comment]
Please reopen if this is still of interest.
