### ISSUE TITLE
any plan to distribute this through npm ?

### ISSUE THREAD

**Issue by parmentelat** [rajgoel/reveal.js-plugins#46]
Hey there

as stated in the header, it seems like it would make a lot of sense to expose this cool stuff to `npm` so that it can be installed through a dependency in `package.json``

Any plan to go down this road ?

thanks in any case

**Comment by parmentelat** [comment]
well, as you know it's the de facto standard for publishing javascript code  
a bit like pip for python, if that's more helpful

in any case there is an intro online here
https://docs.npmjs.com/getting-started/publishing-npm-packages

now to be honest I have always been on the `npm install` end of things, it's really convenient indeed, but have no hands-on experience from the `npm publish` side of the equation ;)

thanks

**Comment by parmentelat** [comment]
Hi there again 

How interested are you about having this module ship through npm ?

Specifically our use case is this: I am a contributor to RISE https://github.com/damianavila/RISE that is a slideshow viewer for jupyter notebooks

we have a pending PR https://github.com/damianavila/RISE/pull/355 that is about pre-shipping chalkboard, and for that to work smoothly it would be of great help if we could just use `npm install` instead of having to replicate part of your repo inside ours

I'd like to know how you feel about that at all, so that we can see if/how we can help in this area

Thanks anyways

**Comment by rajgoel** [comment]
Hi,
my feeling about npm is that I see that it is useful for some folks, however, I do not know whether I can dedicate time to this. So far I only focused on the code and not on the distribution. 

Thus if shipping through npm only requires a PR, a few initial (fool-proof) steps, and little effort to maintain, I'd be glad to include this. Considering improving of the distribution of the software, I guess I also need to start thinking of publishing releases. Help in these directions would be very appreciated.

**Comment by rajgoel** [comment]
@parmentelat  Just published ```reveal.js-plugins``` on npm. Thanks for your contribution!
