### ISSUE TITLE
Did anyone make chalk plugin work with org reveal?

### ISSUE THREAD

**Issue by cryoguy** [rajgoel/reveal.js-plugins#48]
Did anyone make chalk plugin work with org reveal?
I got a blank html with following code:
`#+REVEAL_PLUGINS: (chalk)
#+REVEAL_EXTRA_JS: ./revealjs_chalk.js`

**Comment by rajgoel** [comment]
Sorry, I can't help here. Closing this issue, but please feel free to add a solution if you find one.
