### ISSUE TITLE
How does the embed_tweet work? 

### ISSUE THREAD

**Issue by florestan1804** [rajgoel/reveal.js-plugins#49]
Hi, I am new to reveal.js because I'd like to have an easy plugin for how to include tweets into a presentation. I found your plugin which seems to be really cool. But when I follow both the reveal.js installation guideline and your guideline for embed_tweet, I only get a blank page back. Does anyone see my error in using the plugin? 

    <!doctype html>
    <html lang="en">    
    <head>
        <meta charset="utf-8">
        <title>Reveal.js 3 Slide Demo</title>
        <link rel="stylesheet" href="css/reveal.min.css">
        <link rel="stylesheet" href="css/theme/default.css" id="theme"> 
        
        
    </head>

    <body>
        
        <div class="reveal">
            
            <div class="slides">

                
                
                <section>
                    <div class="tweet" data-src="https://twitter.com/marcfbellemare/status/972558957645631488"></div>
                </section>

            </div>
        </div>
        <script src="lib/js/head.min.js"></script>
        <script src="js/reveal.min.js"></script>

        <script>
            // Required, even if empty.
            Reveal.initialize({
            // ...
                 dependencies: [
                    // ... 
                    { src: 'plugin/embed-tweet/embed-tweet.js' },
                    // ... 
                ]
            });
         </script>
    </body>
    </html>

**Comment by rajgoel** [comment]
Hi, I suggest you try to modify the [demo](https://rajgoel.github.io/reveal.js-demos/embed-tweet-demo.html) to work on a running code. You can find the source code of the demo here: https://github.com/rajgoel/reveal.js-demos

**Comment by florestan1804** [comment]
Thanks for advice & the plugin, works fine now!
