### ISSUE TITLE
[chalkboard] Inconsistent handling of small marks

### ISSUE THREAD

**Issue by rmcrowley2000** [rajgoel/reveal.js-plugins#52]
I've been testing out the chalkboard plugin across different browsers, and noticed that the handling of small marks (dots or the like) seems inconsistent, and in the case of Chrome, entirely missing.  This makes any sort of writing nearly impossible with most browsers, since you can't use characters like `i j . :`, as well as superscripts and subscripts.  As someone who uses reveal.js for lecturing, this is quite problematic.

It appears the cause of the issue is that, in Chrome and Firefox, touch event listeners are forced to be passive by default.  As a consequence, the initial touch point registers at the correct place but at a later time, once the touch input has moved a relatively far distance away.  The second event to register is then this farther point, leading to ignoring all interim movement.  After the second registered point, everything works as expected.

Browsers tested:

- Windows 10, Chrome 69.0.3493.3 (dev) and 67.0.3396.99 (base): Doesn't register small marks using touch, stylus, or mouse.  Small jittering while writing doesn't register either  
- Windows 10, Firefox 61.0.1: Doesn't register small marks normally, but will on double tap if using a stylus.
- Windows 10, Edge: Works consistently with a pen. Requires slight movement for other input methods.
- Linux, Chrome 69.0.3464.0: Doesn't work with mouse (no touch/stylus for this machine).

The above matches with what you would expect, since Edge does not force passive handling.

I found a fix for Chrome, and have posted a PR for it: https://github.com/rajgoel/reveal.js-plugins/pull/51

I'm adding this Issue as well though, as my fix doesn't seem sufficient for Firefox.

Workaround: Use Edge.

**Comment by rajgoel** [comment]
@rmcrowley2000 Thanks a lot for your feedback and sorry for the very late response. I can confirm that dots are not drawn. This is because my implementation requires at least a small move to distinguish simple clicks from drawing (if I remember correctly). When drawing dots or colons etc. I always draw a very small circle as a workaround and never found this to be a real problem (using a pen). 

Thanks a lot for your PR. At the moment I am hesitating to merge it because it looks like a weird workaround and not a real solution to the problem. I'll keep it in mind when I find more time to work on it.

**Comment by rmcrowley2000** [comment]
@rajgoel The PR isn't so much a workaround.  It used to be that the default value for `passive` for touchstart and touchmove was false, per the specification.  Due to some undesirable effects of these being non-passive, Chrome and Firefox changed the default for `passive` to be true.  All my PR does is make it explicit that this handler needs to be non-passive.  The rest of the code in there is to maintain compatibility with Internet Explorer, since it doesn't have a `passive` option.  To some extent, maybe there is a better solution, but the PR is a solution in that it directly fixes a regression caused by changes in the browsers.  As long as you use touchstart and/or touchmove, you'll need to include something like what is in the PR.

The exact details are covered in [Mozilla's dev page](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#Improving_scrolling_performance_with_passive_listeners).  In other words, this plugin would have worked perfectly on Chrome 54 and earlier and Firefox 60 and earlier, but Chrome 55 and Firefox 61 made breaking changes that broke this.

I'm still using the code from my PR in my day-to-day teaching on the up-to-date Chrome and Chrome dev versions without issue.
