### ISSUE TITLE
Documentation :: Wrong Code

### ISSUE THREAD

**Issue by blackat** [rajgoel/reveal.js-plugins#54]
Hello, 
I have found the code to be copy/paste is not correct, you should remove 

```
<pre><code data-trim>
```

then it works like a charm ;-)
Thanks a lot for the plugin, really cool stuff.

**Comment by rajgoel** [comment]
Thanks for your feedback. Could you please be a bit more specific to where the wrong line is (i.e. which plugin, which section of the documentation)?

**Comment by blackat** [comment]
@rajgoel really sorry, it in the Embed Tweet Plugin 😄 

`<pre><code data-trim>
	<div class="tweet" data-src="TWEET_URL"></div>
</code></pre>`

otherwise the tweet is not rendered.

**Comment by rajgoel** [comment]
You are right. Thanks for the feedback.  :star: 

Just fixed it.
