### ISSUE TITLE
[Chart] Is it possible to add a chart title?

### ISSUE THREAD

**Issue by fralik** [rajgoel/reveal.js-plugins#55]
Hi!

I can't figure out if it is possible to add a title to chart? Tried:

```
<!--
{
    "options": {
        "title": {
            "text": "my title",
        }
    },
}
-->
```
I have a single dataset and when I add an option like above, a new dataset color appears in legend.

**Comment by rajgoel** [comment]
The plugin is just a wrapper, so anything that works with Chart.js should also be doable with the plugin. Thus anything related to configuring charts should be explained in the Chart.js documentation https://www.chartjs.org/docs/ , for issues related to using the plugin you may look at the source of the demo https://github.com/rajgoel/reveal.js-demos/blob/master/chart-demo.html
