### ISSUE TITLE
[Anything] Toggle visibility of text/fragment which resets to invisible on Next/Previous

### ISSUE THREAD

**Issue by r2bw** [rajgoel/reveal.js-plugins#56]
It seems to me anything.js could allow me add a function that would store answers to questions in an html comment and with a key press reveal the answer ( in a span or as a fragment). 

<p><span class="answer"></span></p>

When the spacebar/arrow keys are pressed the answer would revert to being hidden and the presentation would animate to the next/previous slide  as appropriate. 

The problem is I have very little javascript knowledge and I keep getting errors when i try to call the function with a key. If this problem is not too difficult to solve I'd really appreciate any help.

Richie

Reveal.addKeyBinding( {keyCode: 114, key: 'r', description: 'Reveal Answer'}, function() {
					anything: [ 
					{ className: "answer",  
					  initialize: (function(container, options)
					  {container.innerHTML = options.answer}
					  ) 
					},
				 // ...
				]
			} )

**Comment by rajgoel** [comment]
What you want to achieve is certainly possible. You might be able to find ideas how to implement your functionality by looking at the source of the documentation https://github.com/rajgoel/reveal.js-demos/blob/master/anything-demo.html
Alternatively you could also include a div in the container for which you change the visibility from ```display:none``` to ```display:inline``` (see https://www.w3schools.com/css/css_display_visibility.asp)
