### ISSUE TITLE
How to add dependencies in jupyter notebook

### ISSUE THREAD

**Issue by HaiBethel** [rajgoel/reveal.js-plugins#57]
Thanks for this wonderful plugin, Goel.

I am quite new to this area so I do not know how to add the dependencies to the reveal presentation of jupyter notebook. Can you suggest how to do that?

**Comment by rajgoel** [comment]
Sorry, don't have any experience with jupyter. May be this https://github.com/rajgoel/reveal.js-plugins/pull/50#issuecomment-512966677 is of help
