### ISSUE TITLE
Update menu submodule

### ISSUE THREAD

**Issue by clayt85** [rajgoel/reveal.js-plugins#58]
By default, the [menu](https://github.com/denehyg/reveal.js-menu) submodule is pointing to commit 97d8561 (tag 0.6.0).  There have been quite a number of nice improvements since that time.  Perhaps time to update the commit that is being tracked?

(FWIW: In my local repo, I moved the menu commit all the way to the latest commit on the master branch.  I had to update a few font-awesome paths, but everything worked just fine.)

**Comment by rajgoel** [comment]
Finally done :-)
