### ISSUE TITLE
Can't make it work with external markdown

### ISSUE THREAD

**Issue by nakednous** [rajgoel/reveal.js-plugins#59]
I want to make a plot with the plugin, but can't make it work with an external markdown file. I guess it has to do with the way the html comments are parsed. I tried adding an extra hyphen to the comments mark (), but it didn't work either.

Is there a workaround for this?

**Comment by mw75** [comment]
Works fine for me!
Whats the problem on your side?

**Comment by dalgaaf** [comment]
This works fine for me:
`
<canvas data-chart="line">

</canvas>
`

**Comment by rajgoel** [comment]
@dalgaaf Thanks a lot for providing an example!
