### ISSUE TITLE
[chart] Moment.js not found

### ISSUE THREAD

**Issue by roccomuso** [rajgoel/reveal.js-plugins#6]
I'm having this warning:

    Chart.js - Moment.js could not be found! You must include it before Chart.js to use the time scale. Download at http://momentjs.com/

But i did include moment.js in my dependencies and before Chart.js file.

Initially I've not included <code>csv2chart.js</code> because I thought I don't want to use CSV files etc. But then I realized that it is mandatory, because it is the plugin core. I guess the name should be changed, a bit misleading.

Moreover, i'd like to "animate" my chart when i come over the slide containing it, (i'd like to have the same effect shown on the chartjs.org > ***"Six chart types"*** section. Any tips about it?

**Comment by rajgoel** [comment]
The animate feature doesn't work at the moment because the charts are created upon load (and animated without being visible). Currently, there is no (or at least I don't know of ) way to restart the animation.

Is the warning creating any issues except for appearing in the console?

**Comment by roccomuso** [comment]
@rajgoel the warning is not creating issues.

**Comment by rajgoel** [comment]
Thanks, closing this for now. Please reopen if you find any issues.

**Comment by rajgoel** [comment]
With the final release of Chart.min.js v2.0.0 the warning about Moment.js should no longer appear.
