### ISSUE TITLE
[chalkboard] Can chalkboard work with the multiplexer?

### ISSUE THREAD

**Issue by henrylaxen** [rajgoel/reveal.js-plugins#7]
I am giving a presentation, where I would like to use the multiplexer to control the student's devices, and fire up the chalkboard to add details.  Unfortunately, it seems that what I write on my master presentation does not appear on the _client's_ screen.  Would it be possible to add this feature, or am I perhaps doing something wrong?  I can control the _client's_ screen from my master, but whatever I write on my screen does not appear on theirs.  Thanks in advance for any help.
Best wishes,
Henry Laxen

**Comment by rajgoel** [comment]
Currently, the chalkboard plugin does not support the multiplexing. I haven't used multiplexing myself, but generally this would be a great enhancement. 

As far as I understood, the multiplex plugin currently only supports the basic Reveal.js events and no custom events. Thus, adding multiplex support to the chalkboard plugin would require to also change the multiplex plugin.

**Comment by dharvey24** [comment]
I'd be really interested to learn how to get this plugin to work with the Notell Multiplex add-on, even with the limitation of having just the host screen display the chalkboard.  All help in installing this is much appreciated.  I've placed the files in the reveal/plugin folder etc and can see the pen images when I start the server, but clicking on them doesn't seem to do anything.

**Comment by rajgoel** [comment]
I don't know of any reason why the plugins should not work side-by-side within the same slide show. Have you checked that you can have each plugin working without the other? Can you create a minimal example where using both would not work? If yes, please create a separate issue where you post this example.

It may be that the problems you have are related to the [default settings](https://github.com/rajgoel/reveal.js-plugins/tree/master/chalkboard#configuration) of the plugin which prevent users to change existing drawings. You can change the default settings by 

```
Reveal.initialize({
    // ...
    chalkboard: { 
        // ...
        readOnly: false,
        // ...
    },
    // ...
});
```

**Comment by cerisara** [comment]
The broadcast plugin is deprecated I think... So, how can we send now the chalkboard drawings to the multiplex clients ? (Very useful in distant classrooms ! )

Thanks a lot for your plugins.

**Comment by rajgoel** [comment]
@cerisara  Have you considered asking for a feature of the [multiplex plugin](https://github.com/reveal/multiplex) allowing to transmit custom events? Once this is possible it should be possible to setup the chalkboard plugin to use the multiplex channel to send drawings to clients.

**Comment by cerisara** [comment]
Hi back: I've modified both the multiplex and chalkboard plugins to make them compatible one with the other:
https://github.com/cerisara/multiplex

It seems to work, I mean, you can draw on the master slides and the drawing is sent to the client sides. More testing with various browsers is still to be done. And also there's still an annoying Y-shift when zooming too much, but overall, it's usable.

**Comment by rajgoel** [comment]
@cerisara: Thanks for your interesting work. I had a brief look at your solution. I didn't quite understand why you had to change the chalkboard-plugin to send the events. The chalkboard-plugin already dispatches events that the (now frozen) broadcast-plugin caught and processed. Wouldn't it be possible to have all changes within the multiplex plugin?

**Comment by cerisara** [comment]
@rajgoel Thanks for your reply: you're right, I should try and process these events. However, there's a problem I don't know how to solve so far: it's about positioning correctly the drawing on the client. And my guess is that it depends on both the levels of zooming in the master and client browsers (and probably not only that !): I'm not sure this information is sent by the master in these events, so there may need to be some modifications in the chalkboard as well.

**Comment by rajgoel** [comment]
@cerisara The broadcasting functionality of the chalkboard plugin should automatically deal with the scaling and positioning. 

**Background:** each drawing canvas has a height and with attribute (if I remember correctly, these are taken from the reveal config). All x,y coordinates are sent w.r.t. these values (even if the host resizes the window). The client receives the values sent by the host without changes. If the client canvas has a different size, the resizing is done w.r.t. the client canvas size and the height and weight of the host (or the reveal config). That's the design, should there be a bug let me know.

In any case, if you manage to create a version of the multiplex plugin that can receive and send the events of the chalkboard plugin without changes, I could take a look at it and check the scaling issue.

**Comment by cerisara** [comment]
@rajgoel Thank you for your input; indeed, I'd prefer to already get the normalized (x,y) from chalkboard, but I had the feeling that this normalization process does not handle zooming (which is
done at the browser level, and it's very hard to get the zooming factor from JS). This can even be tested locally: after drawing, if you zoom in, then the drawing does not adapt correctly afaik. When you have a master + client, both may not have the same zoom level to start with...
But I might not have understood all this correctly.

**Comment by rajgoel** [comment]
@cerisara "Zooming" understood as zooming inside the browser is not supported by the chalkboard-plugin (and unlikely to be supported in the future), "Zooming" understood as resizing the browser window should work out of the box. I guess you are referring to the first. If you can live without this zooming, the master/client scaling should work if the client has a different screen size.

**Comment by cerisara** [comment]
@rajgoel Thank you for the info. I modified multiplex to use your "send" and "received" events, and tried without any browser-zooming, but with different window sizes: it works, but does not scale the (x,y) correctly; it keeps the same size as the source browser. May it be because I've not passed any "init" event to the client ?

**Comment by rajgoel** [comment]
@cerisara Do you have a demo available where I can see the problem? I could try to take a look to see why scaling doesn't work. First guess would be that the initial width & height are not broadcast for some reason. Maybe they don't even need to be broadcast because it might be assumed that height and weight are explicitly set in the reveal config. If I can reproduce the problem it might be easy to resolve.

**Comment by cerisara** [comment]
Thank you for your time. Here is a demo, with the original chalkboard plugin (unmodified) and the modified multiplex plugin (master branch [here](https://github.com/cerisara/multiplex)); you should open both URLs in different windows:

http://talc2.loria.fr/xtof/mplex/demoMaster.html
http://talc2.loria.fr/xtof/mplex/demoClient.html

Thanks !

**Comment by cerisara** [comment]
Some progress: it's working with the correct scaling, the problem was indeed that I had to send "init" to the chalkboard...
But:

- there's still some error messages from the chalkboard, I've got to try and get where they come from
- I had to modify a bit the chalkboard, so that it sends an event when doing "toggleNoteCanvas"

**Comment by cerisara** [comment]
OK the error comes when the delay between the "init" and "startDrawing" events is too short... :-/

**Comment by cerisara** [comment]
OK, I modified the init process (see https://github.com/cerisara/multiplex/) : now the master has to press "a" to send the init command to the chalkboard; hence, there is enough delay when pressing later on "c". And I don't need any more to modify the chalkboard.
But this is a workaround: the main problem is that the multiplex cannot easily warn the master when there is a new client that connects; so I used this "a" key from the master instead to do that. The fun part is that if we don't press "a", drawings are sent to the clients, but without correct scaling. Then, as soon as the master press "a", drawings get repainted with the right scaling.
But well, it's not fully satisfying obviously...

**Comment by rajgoel** [comment]
Good to see that you progress. You say that  the error comes when the delay between the "init" and "startDrawing" events is too short. If the problem is that "startDrawing" is already executed while "init" is not yet completed, one could set a flag in the "init" part and delay execution of all other events until "init" is completed:

https://github.com/rajgoel/reveal.js-plugins/blob/8127033db8a223497d66ebddea08d4e829c7d297/chalkboard/plugin.js#L789-L851

What do you think?

**Comment by cerisara** [comment]
I agree, this looks like a nice solution, and may help to solve a few other instabilities that I have noted. Will try that later on when I have some time. I hope it won't create new problems like events queue overflow ;-)

**Comment by cerisara** [comment]
Hmm, after some reading, I don't think any more that this was the problem: especially as JS uses an event loop model, which prevents concurrent events to execute. Also by doing more testing, I've identified a consistent behavior: the "newclient" event is not enough, as it does not have the correct storage values; so the master actually needs to press BACKSPACE to force a reset of the storage on the master and send it to the clients. Then it works, and no need for an additional key, but it's still a bit annoying. 

So, from the point of view of the chalkboard, the main point concerns the storage: why doesn't it have the "right" values right from the start ? Why must I press BACKSPACE to set these values ?

But the main TODO is a big change to do on the multiplex to get the info when new clients connect, but it does not concern the chalkboard and I'll try and open an issue about it at multiplex.

Thank you !

**Comment by rajgoel** [comment]
With 4f2975eaf59e52f3c4633909105ae6575a50e8ed and https://github.com/reveal/multiplex/pull/9 chalkboard now works with multiplexing :rocket:

**Comment by rajgoel** [comment]
the new seminar plugin https://github.com/rajgoel/reveal.js-plugins/tree/master/seminar can now be used to broadcast chalkboard drawings and more
