### ISSUE TITLE
typo in sample configuration 

### ISSUE THREAD

**Issue by eneftci** [rajgoel/reveal.js-plugins#72]
Hi

I think the equal signs in your configuration example should be colons:

        penWidth = 3,
        chalkWidth = 7,
        chalkEffect = 1.0,
        erasorDiameter = 20,
        smallDefaultCursors = false,

        penWidth : 3,
        chalkWidth : 7,
        chalkEffect:  1.0,
        erasorDiameter : 20,
        smallDefaultCursors : false,

**Comment by rajgoel** [comment]
Thanks! Fixed.
