### ISSUE TITLE
embed-tweet, can it load a Tweet that was appended (after initial slides already rendered)?

### ISSUE THREAD

**Issue by sgornick** [rajgoel/reveal.js-plugins#76]
I have the need to dynamically append a slide that includes a Tweet once the initial slides have already been rendered.  I'm doing this in the following snippet of code:

```
dom = {},
dom.slides = document.querySelector( '.reveal .slides' );
slide = document.createElement( 'section' );
slide.classList.add( 'tweet', 'future' );
slide.setAttribute('data-src', 'https://twitter.com/jack/status/20');
dom.slides.appendChild(slide);
```

When I append a slide this way **before** the slides are first rendered, it works fine.

If I append the slide the exact same way, but instead do this **after** the slides have already been rendered, then no Tweet is displayed in that slide that was appended.

I took a look at the embed-tweet.js code, and see how load() is run on ready().  I'm suspecting I need to have it redo the load(), but I don't understand Javascript enough to know what the code needs to do to support this, or even to know if it is possible to render an appended slide that has a Tweet.

My index.html.is in [this gist](https://gist.github.com/sgornick/2d9c2702fd8244e0a62953dc1f26130f).  I'm using the latest embed-tweet.js from master (Nov 17, 2017), and the latest reveal.js (v3.9.2).

Would anyone be willing to point me in the right direction? Or describe how I can put in a method to accommodate a load() of one ore Tweets after the initial rendering has already occurred?

Thank you.

**Comment by rajgoel** [comment]
I just added a simple API. Can you please check whether adding this line
```
RevealEmbedTweet.refresh();
```
after adding the slides solves your problem?
