### ISSUE TITLE
Blackboard mode chalk is not visible

### ISSUE THREAD

**Issue by steven-varga** [rajgoel/reveal.js-plugins#78]
Great work!  I upgraded from v0.6 to v0.9 and noticed the chalk doesn't do anything when in blackboard mode. This can be reproduced with the demo link and the following browsers. Does anyone else have similar behaviour? 
- works well when drawing on slides.

**windows**: Version 81.0.416.68 (Official build) (64-bit)
**linux**: Version 80.0.3987.132 (Official Build) (64-bit)

**Comment by rajgoel** [comment]
Can you provide more details on how to reproduce this issue. I just tried on FF/Android and it works as expected. Are you referring to Chrome, FF, ... ? Are there any error messages on the console (can be seen when going to dev tools in the browser menue)

**Comment by steven-varga** [comment]
Thank you for the quick response. It was my mistake: everything works as advertised; with the exception of the cross hair. 

The problem was with my presentation setup: when setting width + height to 100% the background grid of chalkboard is not visible; nor the chalk leaves mark on surface. I [uploaded the site,](https://github.com/steven-varga/reveal) if any interest
```
Reveal.initialize({ 
   //width: '100%',
   //height: '100%',
   controls: true,
    progress: true,
...
)}
```    	    	
BTW: I am trying to broadcast the chalkboard events to all clients, do you happened to know if such exists or perhaps the best spot to start?

**Comment by dafrenchyman** [comment]
I'm running into the exact same issue. Same way to fix it as well, if I don't 100% the width and height it works.

**Comment by rajgoel** [comment]
Possible, the height and width require absolute values (given in pixel) to determine the scaling factors properly. Not sure whether this can be fixed easily.
