### ISSUE TITLE
[audio-slideshow] Synced video does not show progress in Firefox

### ISSUE THREAD

**Issue by frederik-elwert** [rajgoel/reveal.js-plugins#79]
I noticed a very strange behaviour when setting `data-audio-controls="true"` on `<video>` in Firefox: When the slide with the video comes up, the audio plays correctly, but the video only shows the start frame. However, when I pause using the audio controls, the video “jumps” to the same position. When clicking play again, both audio and video progress correctly.

OTOH, when not using `data-audio-controls` but instead setting `autoplay="true"` on the video, both audio and video start immediate playback.

In Chromium, the video plays correctly with `data-audio-controls`, but does not play with `autoplay`, unless I also set `muted="true"` (which is probably due to their autoplay policy).

**Comment by rajgoel** [comment]
Not sure what caused this behaviour. Anyhow, something was wrong with the event handler, this is fixed in the new version for reveal.js v4.0.2. Please reopen if the problem still exists.
