### ISSUE TITLE
[chalkboard] Compatability with reveal.js v4.0.0 - Chalkboard hiding presentations

### ISSUE THREAD

**Issue by ViralSymphony** [rajgoel/reveal.js-plugins#80]
Reveal.js v4.0.0 was just released with some breaking changes, including updates to the way reveal.js plugins are created and initialized.

When including chalkboard in a reveal.js presentation, the chalkboard background seems to overlay on top of the presentation, hiding everything beneath it. The keyboard bindings work as expected, but when toggling the Chalkboard, the chalkboard (and any drawings on it) don't seem to hide. The cursor also doesn't change back to a mouse pointer, it remains at the chalk. Eraser functionality seems to be okay here, the cursor toggles and lines are erased when used.

I am unsure how notes canvas works with reveal.js 4.0.0 since the slides are being occluded by the chalkboard.

**Comment by rajgoel** [comment]
Hi, thanks for the important info on the update. I will have a look at it as soon as possible.

**Comment by PatrickMassot** [comment]
Any news? The current situation is very confusing for new users since https://revealjs.com/ displays no warning saying that a giant compatibility breaking version just went out. It simply links to this repository in the plugin list.

**Comment by hakimel** [comment]
Hey all. I just tested most of the plugins in this repo and only ran into issues with the chalkboard so far. Fullscreen, Chart, Embed Tweet, Spreadsheet and Custom Controls seem to work as intended as far as I can tell.

I'm looking into what it will take to fix the chalkboard plugin next, if it's an easy fix I'll submit a PR.

**Comment by PatrickMassot** [comment]
Awesome, thank you very much!
