### ISSUE TITLE
[Chart] [reveal.js v4]SyntaxError: expected expression, got '<'

### ISSUE THREAD

**Issue by its-thomas** [rajgoel/reveal.js-plugins#81]
Hi there,

your excellent Chart plugin unfortunately doesn't seem to be compatible with latest Reveal.js 4.0.0.

Console output is:
`SyntaxError: expected expression, got '<'`
regarding both Chart.min.js and csv2chart.js

You think you can fix this issue?

All the best,
Thomas

**Comment by kotborealis** [comment]
I've managed to get Chartjs working with Reveal v4, I'll try to update this plugin a bit later.
