### ISSUE TITLE
[mathsvg] SVG files created with python matplotlib loose latex labels

### ISSUE THREAD

**Issue by csiegl182** [rajgoel/reveal.js-plugins#88]
I try importing SVG generated by python matplotlib into my reveal.js presentation. These svg contain latex labels, which should be converted by the mathsvg plugin. Unfortunately, these labels are not shown at all.

The reason is that the <g> tag of such SVG files has no "font-size" attribute in order to calculate the scaling for the resulting latex output. Hence, the <g> tag has size zero and is not shown.

**Comment by rajgoel** [comment]
I had to remove non-core plugins to reduce my workload maintaining this project. As a consequence, the mathsvg plugin is no longer maintained, sorry.
