### ISSUE TITLE
[chalkboard] Chalkboard does not work propperly together with Speaker View

### ISSUE THREAD

**Issue by JanoschDeurer** [rajgoel/reveal.js-plugins#9]
I realy like this plugin, and it would be great if it would work together with the Speaker View. If I open the Speaker View I can draw in both windows, but the drawings are not synced in any way.

**Comment by rajgoel** [comment]
Thanks for the feedback. I haven't used the speaker note myself and never had a look at how it technically works. The problem is that the plugin currently does not have any synchronisation feature implemented and I do not have any plans to do so. Please feel free to check if you can implement this feature and create a PR.

**Comment by joneuhauser** [comment]
I ran into the same limitation: chalkboard drawing works in the speaker view, but the drawing events are not synchronized between the speaker view and the main presentation.

We can reuse the broadcasting / receiving code for multiplex mode to get this to work.
`BroadcastChannel` would be preferable, but at least on github-pages I only got `localStorage` write + polling to work.  

  ```js
function suppressChalkboardDebugLogs() {
    if (console.__kitChalkboardDebugFilter) return;

    const originalLog = console.log.bind(console);
    console.log = (...args) => {
      const isChalkboardDebug = args.some((arg) => {
        if (typeof arg === "string") return arg.includes("chalkboard-plugin");
        try {
          return JSON.stringify(arg).includes("chalkboard-plugin");
        } catch {
          return false;
        }
      });

      if (!isChalkboardDebug) originalLog(...args);
    };

    Object.defineProperty(console, "__kitChalkboardDebugFilter", {
      value: true,
    });
  }

  function setupChalkboardSync() {
    suppressChalkboardDebugLogs();

    const source =
      globalThis.crypto?.randomUUID?.() ?? `${Date.now()}-${Math.random()}`;
    const storageKey = "kit-chalkboard-sync-message";
    let lastStorageMessage = "";

    const replay = (content) => {
      const event = new CustomEvent("received");
      event.content = content;
      document.dispatchEvent(event);
    };

    const readStorageMessage = () => {
      const value = localStorage.getItem(storageKey);
      if (!value || value === lastStorageMessage) return;

      lastStorageMessage = value;

      try {
        const message = JSON.parse(value);
        if (
          message.source !== source &&
          message.content?.sender === "chalkboard-plugin"
        ) {
          replay(message.content);
        }
      } catch {
        // Ignore stale or malformed sync messages.
      }
    };

    document.addEventListener("broadcast", (event) => {
      const { content } = event;
      if (content?.sender !== "chalkboard-plugin") return;

      lastStorageMessage = JSON.stringify({ source, time: Date.now(), content });
      localStorage.setItem(storageKey, lastStorageMessage);
    });

    window.addEventListener("storage", (event) => {
      if (event.key === storageKey) readStorageMessage();
    });

    // Required in some speaker iframe / GitHub Pages cases where storage events
    // do not reliably fire across contexts.
    window.setInterval(readStorageMessage, 100);
  }
```


  Call it after loading the chalkboard plugin, before or around Reveal.initialize():

  `setupChalkboardSync();`

  One extra note: the plugin currently logs every received synced event here:

  `console.log(JSON.stringify(message));`

  That becomes very noisy during drawing, so the helper above includes a narrow console filter for messages containing chalkboard-plugin. 

  Assumption: the main presentation and speaker view must be same-origin.

Demo: https://joneuhauser.github.io/revealjs-template

**Comment by rajgoel** [comment]
- Please consider a creating a PR to optionally turn off log messages (default: silent). 
- Please also consider creating a PR for your synchronisation idea. Will this add a new dependency? If yes, then please do not make this default behaviour but opt-in for those interested. Also an opt-in behaviour makes it easier for me to check that nothing breaks without it.
