### ISSUE TITLE
[chalkboard]: Not loading with RevealJS 3.9.2

### ISSUE THREAD

**Issue by finnito** [rajgoel/reveal.js-plugins#90]
Kia ora,

I am using RevealJS 3.9.2 because I use it with Pandoc, and Pandoc does not support RevealJS 4 yet.

I have added it to my reveal.js configuration like so:

```
// A list of registered reveal.js plugins
plugins = {
    { src: '/reveal.js/plugin/chalkboard/chalkboard.js', async: true }
},
// A key:value map of shortcut keyboard keys and descriptions of
// the actions they trigger, generated in #configure()
keyboardShortcuts = {
    67: function() { RevealChalkboard.toggleNotesCanvas() },    // toggle notes canvas when 'c' is pressed
    66: function() { RevealChalkboard.toggleChalkboard() }, // toggle chalkboard when 'b' is pressed
    46: function() { RevealChalkboard.clear() },    // clear chalkboard when 'DEL' is pressed
     8: function() { RevealChalkboard.reset() },    // reset chalkboard data on current slide when 'BACKSPACE' is pressed
    68: function() { RevealChalkboard.download() }, // downlad recorded chalkboard drawing when 'd' is pressed
    88: function() { RevealChalkboard.colorNext() },    // cycle colors forward when 'x' is pressed
    89: function() { RevealChalkboard.colorPrev() } // cycle colors backward when 'y' is pressed
},
```

I even added this to `chalkboard.js` so that Fontawesome is loaded, as I did not previously use it.

```
document.getElementsByTagName("head")[0].insertAdjacentHTML(
	    "beforeend",
	    "<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css\" />");
```

And I have verified that all the correct network requests go out loading `chalkboard.js` and the associated images.
The problem is that it does not appear to have been triggered, and therefore the keybindings don't work, and nor do the control appear on screen.

Is there some incompatibility with how the plugin is initialized?

**Comment by rajgoel** [comment]
Sorry, I won't be able to help you here. I just updated the plugins for reveal.js v4.0.2 and will no longer support v3.9.x. The plugins will still be available in a branch 'v3' and you might want to look at the 'v3' on https://github.com/rajgoel/reveal.js-demos. Regarding Pandoc, I do not have any experience.
