### ISSUE TITLE
[Broadcast] disable video

### ISSUE THREAD

**Issue by juanerasmoe** [rajgoel/reveal.js-plugins#93]
Can broadcast be used without the video? I just want the broadcast chalkboard effects (not possible with multiplex plugin AFAIK) and I'm not sure if I have enough resources to broadcast live video as well.

**Comment by rajgoel** [comment]
I had to stall the development of the broadcast plugin and  moved it to https://github.com/rajgoel/reveal.js-broadcast. For the moment, I won't be able to look at this, sorry.
