### ISSUE TITLE
how to determine audio-slideshow is over ?

### ISSUE THREAD

**Issue by zfang1995** [rajgoel/reveal.js-plugins#98]

**Comment by rajgoel** [comment]
it stops automatically

**Comment by zfang1995** [comment]
> it stops automatically

sorry for my bad expression, actually I mean I want to execute a callback function after the audio-slideshow finished playing, so how to know that it happened.

**Comment by rajgoel** [comment]
The plugin sends an event when playback is paused (and probably when the slideshow is completed - not sure)

```
document.dispatchEvent( new CustomEvent('stopplayback') );
```

You might want to add an event listener to react on this event.

**Comment by zfang1995** [comment]
thanks!

**Comment by zfang1995** [comment]
I solved this now, and here's what I did.
#99
